name: Deploy n8n

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy repo to server (SCP)
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "."
          target: "/opt/n8n"

      - name: Create .env on server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            set -e
            sudo mkdir -p /opt/n8n
            sudo chown -R $USER:$USER /opt/n8n
            cd /opt/n8n
            cat > .env << 'EOF'
            DOMAIN=${{ secrets.DOMAIN }}
            LE_EMAIL=${{ secrets.LE_EMAIL }}
            N8N_ENCRYPTION_KEY=${{ secrets.N8N_ENCRYPTION_KEY }}
            N8N_BASIC_AUTH_ACTIVE=${{ secrets.N8N_BASIC_AUTH_ACTIVE }}
            N8N_BASIC_AUTH_USER=${{ secrets.N8N_BASIC_AUTH_USER }}
            N8N_BASIC_AUTH_PASSWORD=${{ secrets.N8N_BASIC_AUTH_PASSWORD }}
            EOF

      - name: Pull & up
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            set -e
            cd /opt/n8n
            docker compose pull
            docker compose up -d
            docker compose ps